### ISSUE TITLE
Feature Request: `jx promote --batch-mode`

### ISSUE THREAD

**Issue by tomhobson** [jenkins-x-plugins/jx-promote#132]
With jenkins-x v1 we really enjoyed being able to take the requirements.yaml and update the values from staging in one file in an understandable PR for our product team and BA's to review.

Understandably this has changed and is more difficult to do. But promoting services one at a time takes a long time and if you have dependencies it could break them.

We think it would be nice to have the ability to update multiple services at once into production with a batch process.

Something like 
```
user@machine: jx promote --batch-mode
Services to promote (Use space to select and enter to proceed)
[] Product-Service
[x] Payment-Service
[x] User-Service
[] Time-Service

2 services selected

Promoting....
```

(Side note: We've discussed within our team and think we will be able to dedicate some time to this. We just wanted to start discussion and work out how you guys would like it done/if it's something you'd like to do.)

**Comment by jstrachan** [comment]
fixed - see https://jenkins-x.io/v3/develop/environments/promotion/#synchronizing-environments-or-namespaces
